# Nombre del ejecutable
TARGET = SearchersProject

# Compilador
CXX = g++

# Opciones de compilación
CXXFLAGS = -std=c++11 -Wall

# Directorios de código fuente y objetos
SRCDIRS = Dataset knnSearchers TimeSeries
SRCDIR = $(addprefix $(CURDIR)/,$(SRCDIRS))
OBJDIR = obj
BINDIR = bin

# Archivos fuente y objetos
SOURCES = $(wildcard $(addsuffix /*.cpp, $(SRCDIR)))
OBJECTS = $(patsubst $(CURDIR)/%.cpp,$(OBJDIR)/%.o,$(SOURCES))

# Regla principal
all: $(BINDIR) $(TARGET)

$(BINDIR):
	mkdir -p $(BINDIR)

# Regla para el ejecutable
$(TARGET): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ -o $@

# Regla para los archivos objeto
$(OBJDIR)/%.o: $(CURDIR)/%.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Limpieza de archivos temporales y ejecutable
clean:
	rm -rf $(OBJDIR) $(BINDIR)